### ISSUE TITLE
Dark mode support mentioned in docs does not work

### ISSUE THREAD

**Issue by kingyue737** [shikijs/shiki#373]
It requires class with name of theme to use the method below, but the html generated by shiki does not include it
```scss
@media (prefers-color-scheme: light) {
  .shiki.dark-plus {
    display: none;
  }
}
@media (prefers-color-scheme: dark) {
  .shiki.light-plus {
    display: none;
  }
}
```
