### ISSUE TITLE
`verify-intersections`: permitted intersections

### ISSUE THREAD

**Issue by zhangtao25** [shikijs/shiki#592]
### Clear and concise description of the problem

I'm working on a hydrated version of the Istanbul report, and there will be some overlapping tagging situations that will prompt intersections when using the shiki.

### Suggested solution

I would like to be able to turn on whether or not to check for intersections via configuration.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Contributes

- [ ] If this feature request is accepted, I am willing to submit a PR to fix this issue

**Comment by antfu** [comment]
It's just not possible to create that DOM structure - if you have any idea to solve that PR welcome

**Comment by zhangtao25** [comment]
> It's just not possible to create that DOM structure - if you have any idea to solve that PR welcome

I migrated from highlight.js because of the lack of code block decorating functionality. I also investigated Codemirror, but the package size was too big, and all I wanted was block highlighting. shiki provides block decoration, which is very important to me. I plan to check out shiki code and make a PR.

**Comment by czemar** [comment]
I think there is no easy solution, but there is always one - use `transformers`. For example like this:
```typescript
let _code = this.shiki.codeToHtml(code || '', {
      lang: 'typescript',
      theme: 'github-dark-high-contrast',
      transformers: [
        {
          // Split the spaces to new tokens (Required when the highlight starts at the beggining of the word)
          tokens(tokens) {
            const newLines = [];
            for (const line of tokens) {
              const newTokens = [];
              let offset = 0;
              for (const text of line) {
                const tokens = text.content.split(/(?<=\s)(?=\S)|(?<=\S)(?=\s)|(?<=[{}])|(?=[{}])/).map(token => {
                  const tokenOffset = text.content.indexOf(token, offset);
                  offset = tokenOffset + token.length;
                  return { token, offset: tokenOffset };
                });
                newTokens.push(...tokens.map(({ token, offset }) => ({
                  ...text,
                  bgColor: token.startsWith(' ') ? 'transparent !important' : text.bgColor,
                  content: token,
                  offset: offset,
                })));
              }
              newLines.push(newTokens);
            }
            return newLines;
          },
          span(hast, line, col, lineElement, token) {
            // Check if the token should be highlighted
            const decoration = decorations.find(d => {
              const startPosition = d.start as Position;
              const endPosition = d.end as Position;
              return startPosition.line == line && endPosition.line == line && startPosition.character <= col && endPosition.character >= col
            });
            return {
              type: 'element',
              tagName: 'span',
              properties: {
                className: decoration ? decoration.properties!['className'] : null,
              },
              children: [hast],
            };
          },
        },
      ]
    });
```
    
Then we can add some scss to make it visible:
```scss
    .covered, .not-covered {
      position: relative;

      &::before {
        $offset: 6px;
        content: '';
        position: absolute;
        top: #{-$offset / 2};
        left: #{-$offset};
        width: calc(100% + #{$offset * 2});
        height: calc(100% + #{$offset});
        border-radius: 0.5rem;
      }

      span {
        z-index: 1;
        position: relative;
        background-color: transparent !important;
      }
    }

    .covered::before {
      background-color: color-mix(in srgb, var(--ng-doc-success) 20%, #0a0c10) !important;
    }

    .not-covered::before {
      background-color: color-mix(in srgb, var(--ng-doc-alert) 20%, #0a0c10) !important;
    }
```
    
Which gives the result:
    
![image](https://github.com/user-attachments/assets/495d9ace-0f9d-4d64-bd10-1a4a4b8eb57e)
