### ISSUE TITLE
Add examples of twoslash types caching for vitepress with actions/cache

### ISSUE THREAD

**Issue by kravetsone** [shikijs/shiki#840]
It would be good if we will have example of it with easy copy-pasting

Bun install cache example:
```yml
- uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.bun }}-bun
```

What we should add to key hash of lockfile and documentation sources?
